name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - 
  - pip:
      - wandb
      - requests
      - mlflow
      - scikit-learn
      - git+https://github.com/abelix176/nd0821-c3-starter-code#egg=wandb-utils&subdirectory=components
