name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.2.2
  - scikit-learn=0.24.1
  - pip=20.3.3
  - pip:
      - wandb==0.13.2
      - requests
      - git+https://github.com/abelix176/nd0821-c3-starter-code#egg=wandb-utils&subdirectory=components
