name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
    - mlflow=1.14.1
    - scikit-learn=0.24.1
  - pip
  - pip:
      - wandb
      - requests
      - git+https://github.com/abelix176/nd0821-c3-starter-code#egg=wandb-utils&subdirectory=components
