name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - git=2.30.2
  - pip=20.3.3
  - pip:
      - wandb==0.13.9
      - matplotlib==3.3.4
      - pandas==1.2.3
      - mlflow==2.1.1
      - ipython==7.21.0
      - notebook==6.2.0
      - jupyter==1.0.0