name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - cookiecutter
  - hydra-core
  - git
  - pip
  - pip:
      - wandb
      - mlflow
      - ipython
      - notebook
      - jupyterlab
      - matplotlib
      - pandas
