name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - pip
  - pip:
      - wandb
      - pandas
      - mlflow
      - scikit-learn==0.24.1
      - git+https://github.com/abelix176/nd0821-c3-starter-code#egg=wandb-utils&subdirectory=components
