name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pip
  - pip:
      - wandb
      - pandas
      - git+https://github.com/abelix176/nd0821-c3-starter-code#egg=wandb-utils&subdirectory=components
